# Generated by Django 5.2.5 on 2025-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField()),
                ('language', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
